/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

int func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int func_alloc_mem(void);
int func_init_mem(int mem);
void func_free_mem(int mem);
int func_checkout(void);
void func_release(int mem);
void func_incref(void);
void func_decref(void);
casadi_int func_n_in(void);
casadi_int func_n_out(void);
casadi_real func_default_in(casadi_int i);
const char* func_name_in(casadi_int i);
const char* func_name_out(casadi_int i);
const casadi_int* func_sparsity_in(casadi_int i);
const casadi_int* func_sparsity_out(casadi_int i);
int func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define func_SZ_ARG 2
#define func_SZ_RES 2
#define func_SZ_IW 0
#define func_SZ_W 4
#ifdef __cplusplus
} /* extern "C" */
#endif
